service: smishing-archiving-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-1
  stage: dev 
  environment:
    DYNAMODB_TABLE_NAME: EmergingThreatsLabData
    S3_BUCKET_NAME: emerging-threats-image-bucket
    HTML_S3_BUCKET_NAME: emerging-threats-html-bucket
  apiGateway:
    binaryMediaTypes:
      - multipart/form-data
    apiKeys: 
      - APIPhishingKey
  versionFunctions: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:Query
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:GetObject
            - s3:ListBucket
          Resource:
            - arn:aws:dynamodb:us-west-1:*:table/EmergingThreatsLabData
            - arn:aws:s3:::emerging-threats-image-bucket
            - arn:aws:s3:::emerging-threats-image-bucket/*
            - arn:aws:s3:::emerging-threats-html-bucket
            - arn:aws:s3:::emerging-threats-html-bucket/*
plugins:
  - serverless-s3-sync
custom:
  s3Sync:
    - bucketName: emergingthreats-frontend-bucket
      localDir: frontend
      deleteRemoved: true
package:
  exclude:
    - .git/**
    - .vscode/**
    - tests/**
    - '*.md'
    - '*.log'
    - node_modules/aws-sdk/** # AWS SDK is included in the Lambda runtime
    - node_modules/** # Exclude all node_modules to reduce package size
    - dist/node_modules/** # Exclude bundled node_modules
    - dist/tests/** # Exclude test files from the bundled output
    - frontend/** # Exclude frontend files if not needed in Lambda
    - backend/tests/** # Exclude test files
    - node_modules/@aws-sdk/** # AWS SDK v3 is included in the Lambda runtime
    - node_modules/tesseract.js/** 
    - node_modules/openai/** 
    - node_modules/jsdom/** 
    - backend/testing/** # Exclude testing files
    - AWSCLIV2.pkg
  include:
    - dist/**
    - backend/functions/**'
    - frontend/**
    - serverless.yml


functions:
  dataExtractionHandler:
    handler: dist/mainHandler.dataExtraction # Bundled file for dataExtractionHandler
    layers: arn:aws:lambda:us-west-1:688567304941:layer:finalLayer:1
    events:
      - http:
          path: dataExtraction
          method: post
          cors:
            origin: "https://emergingthreats-frontend-bucket.s3.us-west-1.amazonaws.com"
            headers:
              - Content-Type
              - X-Api-Key

            allowCredentials: false

  uploadHandler:
    handler: dist/publicUploadHandler.uploadImage # Bundled file for uploadHandler
    layers: arn:aws:lambda:us-west-1:688567304941:layer:finalLayer:1
    events:
      - http:
          path: upload
          method: post
          cors:
            origin: "https://emergingthreats-frontend-bucket.s3.us-west-1.amazonaws.com"
            headers:
              - Content-Type
              - X-Api-Key
            allowCredentials: false

resources:
  Resources:
    # S3 bucket configuration
    UploadsS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: emerging-threats-image-bucket
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "https://emergingthreats-frontend-bucket.s3.us-west-1.amazonaws.com"
              AllowedMethods:
                - GET
                - PUT
                - POST
              AllowedHeaders:
                - "*"              
    UploadsS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: emerging-threats-image-bucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                AWS: arn:aws:iam::688567304941:role/smishing-archiving-api-dev-us-west-1-lambdaRole
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource: "arn:aws:s3:::emerging-threats-image-bucket/*"
    # S3 bucket for HTML storage
    HTMLS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: emerging-threats-html-bucket
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "https://emergingthreats-frontend-bucket.s3.us-west-1.amazonaws.com"
              AllowedMethods:
                - GET
                - PUT
                - POST
              AllowedHeaders:
                - "*"
    HTMLS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: emerging-threats-html-bucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                AWS: arn:aws:iam::688567304941:role/smishing-archiving-api-dev-us-west-1-lambdaRole
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource: "arn:aws:s3:::emerging-threats-html-bucket/*"
    
    # # The API Key and Usage Plan are managed by Serverless
    # ApiGatewayApiKey:
    #   Type: AWS::ApiGateway::ApiKey  
    #   Properties:
    #     Name: 'APIPhishingKey'
    #     Enabled: true
    #     StageKeys:
    #       - RestApiId: !Ref ApiGatewayRestApi
    #         StageName: dev

    # ApiGatewayUsagePlan:
    #   Type: AWS::ApiGateway::UsagePlan  
    #   Properties:
    #     UsagePlanName: 'ImageUploadUsagePlan'
    #     ApiStages:
    #       - ApiId: !Ref ApiGatewayRestApi
    #         Stage: dev
    #     Throttle:
    #       BurstLimit: 100
    #       RateLimit: 50
    #     Quota:
    #       Limit: 10000
    #       Period: MONTH

    # ApiGatewayUsagePlanKey:
    #   Type: AWS::ApiGateway::UsagePlanKey
    #   Properties:
    #     KeyId: !Ref ApiGatewayApiKey
    #     KeyType: API_KEY
    #     UsagePlanId: !Ref ApiGatewayUsagePlan

  # privateUploadHandler:
  #   handler: backend/functions/privateUploadHandler.uploadImage
  #   events:
  #     - http:
  #         path: private-upload
  #         method: post
  #         cors: true

